### ISSUE TITLE
希望能增加对BedwarsRel1.3.1的支持--这不是玩笑话.

### ISSUE THREAD

**Issue by Qiuscraft** [Ldcr993519867/BedwarsXP#14]
为什么我希望这么做?
我在spigot1.8.8,java 8, BedwarsRel1.3.2-1.3.6的环境下运行起床战争, 由于配置不足的问题, 我希望单端多图而不是bc端, 在打开旁观者模式并关闭bc模式后, 出现了如下问题:
  - 游戏结束后旁观者没有正确退出游戏
  - 游戏结束后旁观者会收到双倍信息, 且右边计分板的人数也有误.
初步猜测是旁观者的某种bug使系统将旁观者“一个人”认成了“两个人”, 导致系统给这个旁观者发送了双倍的信息, 并把旁观者当作“两个人”计入计分板的人数统计中.
事实上, 解决这个问题的方法多种多样, 我曾尝试:
  - 开一个bc端, 游戏结束后自动重启这个子服, 旁观者会被传送到大厅服, 而且服务器重启, 这个bug也就不复存在了, 但是开bc端对配置要求较高, 导致花销较大, 对于小型休闲服来说不值得.
  - 游戏结束后配合插件运行/bw reload命令, 相当于将整个起床战争系统重新加载了一遍, 同样能够解决问题, 但重载时整个服务器会卡主一段时间, 地图很多时, 这段时间相当长, 甚至可以使玩家Time out.
于是我想起以前开服的时候是没有这种情况的, 我怀疑是BedwarsRel版本的问题, 我将版本逐步回退, 并录制视频, 当BedwarsRel版本回退到1.3.1的时候, 这个bug消失了.
如果我对这个问题的描述还不够清楚, 可以查看我录制的视频:
https://www.lanzous.com/i96qtlg
我记得您的这款插件曾经支持BedwarsRel1.2.8版本, 这个版本同样没有旁观者模式的bug, 如果支持1.3.1的版本太麻烦了, 希望您可以给我发一份能支持旧版本BedwarsRel的这款插件.
如有冒犯, 还望海涵.

**Comment by Qiuscraft** [comment]
已经找到了1.6版本的BedwarsXP, 从加载时控制台输出的信息来看, 似乎可以运行.
但是没有经验掠夺功能, 如果能有就更好了xD

**Comment by SakuraKoi** [comment]
看你视频问题出现的原因可能是bwrel没能正确地将玩家的游戏模式从旁观者切换至生存,同时设置了关闭飞行导致向下掉落, 这个问题建议向bwrel处反馈
经验掠夺mcbbs有附属插件

**Comment by Qiuscraft** [comment]
bwrel已经有三年没有更新了, 而bbs的经验掠夺插件似乎没有支持bwrel1.3.1+bwxp1.6, 所以才会在这里反馈.
如果您没有支持老版本的意向的话, 我也许可以尝试着修改一下, 如果公开发布, 我会遵循您在mcbbs上所写的规则.

**Comment by SakuraKoi** [comment]
在同一个jar里面支持新老版本bedwarsrel会是一个噩梦=-=bwrel那class名改完改包名,写这玩意跟写nms似的,每一个版本都得单独做兼容
本插件遵循GPLv2协议,在遵循协议的前提下可以自由修改代码及发布
