### ISSUE TITLE
把敌人打进虚空不会获得经验

### ISSUE THREAD

**Issue by aberter0x3f** [Ldcr993519867/BedwarsXP#15]
击杀玩家后, 玩家的经验将会以经验瓶的方式掉落, 但是如果把敌人打进虚空, 经验瓶会消失, 击杀者不会获得经验.

下面是两种我认为的解决方案:

1. 将经验直接给予击杀者, 取消经验瓶这一个中间步骤
2. 经验瓶 summon 后直接 tp 到最近的玩家身上 (不过这样可能会出现弓箭击杀误判的 bug)

BWrel version: 1.3.7
BWXP version: 1.7

我的配置文件里有这两行:

```
DeathCostXP: 50
DeathDropXP: 100
```

**Comment by SakuraKoi** [comment]
Release本来就是发布版本用的, 速度慢那是你网络问题, 请自行搭梯子
~~好好的Release不用,要百度限速云,没见过这么奇怪的请求~~

**Comment by SakuraKoi** [comment]
Added
