### ISSUE TITLE
大佬，我找不到配置文件呜呜呜

### ISSUE THREAD

**Issue by wangyitong20090425** [Ldcr993519867/BedwarsXP#19]
第一次用github，请问配置文件在那里啊

**Comment by SakuraKoi** [comment]
https://github.com/SakuraKoi/BedwarsXP/blob/master/src/main/resources/config.yml
如果指的是使用插件时的配置文件的话, 启动一次服务端后会自动生成在插件目录下

**Comment by wangyitong20090425** [comment]
好的谢谢您
