### ISSUE TITLE
能在1.12服务器用吗

### ISSUE THREAD

**Issue by MlgmXyysd** [Ldcr993519867/BedwarsXP#2]
开了个1.12服务器，能用不

**Comment by MlgmXyysd** [comment]
好吧并不能

**Comment by SakuraKoi** [comment]
没测试过...
抱歉我这gayhub的chrome自动提醒插件有点问题,没收到提示=-=
(终于有人发issues而不是回复帖子了...热泪盈眶脸.jpg)
