### ISSUE TITLE
建议增加经验限制功能

### ISSUE THREAD

**Issue by bwzzwt** [Ldcr993519867/BedwarsXP#3]
限制可获得的最大经验，避免第一个到金点的玩家获得上千经验

**Comment by SakuraKoi** [comment]
这个我觉得没必要, 抢第一波金的目的不就是为了快速获取大量资源么=-=

**Comment by bwzzwt** [comment]
第一个到金点的玩家获得上千经验，其他玩家只能获得几百经验，你觉得这样公平吗？

**Comment by SakuraKoi** [comment]
很正常啊.......抢资源点的第一波就是为了自己获得优势,这不是常识么=-=

算了丢进开发计划...虽然我觉得除了你没人会用这个功能=-=
再多攒点功能更新就发布新版本

**Comment by SakuraKoi** [comment]
完成
